# Альтернативный поставщик
# ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

# дефолтное значение
ENV['VAGRANT_SERVER_URL'] = 'https://app.vagrantup.com'

Vagrant.configure("2") do |config|
  # Общие настройки для всех машин
  config.vm.box_check_update = false
  config.vbguest.no_install = true

  # ===== WEB SERVER =====
  config.vm.define "web" do |web|
    web.vm.box = "generic/rocky9"
    web.vm.hostname = "web-srv"
    web.vm.network "private_network", ip: "192.168.56.10"
    # web.vm.disk :disk, size: "15GB", primary: true
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "web-server"
    end

    web.vm.provision "shell", inline: <<-SHELL
      dnf update -y
    SHELL
  end

  # ===== First DATABASE SERVER =====
  config.vm.define "db_1" do |db_1|
    db_1.vm.box = "generic/rocky9"
    db_1.vm.hostname = "db-1-srv"
    db_1.vm.network "private_network", ip: "192.168.56.11"

    db_1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "db-1-server"
    end

    db_1.vm.provision "shell", inline: <<-SHELL
      dnf update -y
    #   dnf install -y mysql-server
    #   systemctl start mysqld
    SHELL
  end


    # ===== Second DATABASE SERVER =====
  config.vm.define "db_2" do |db_2|
    db_2.vm.box = "generic/rocky9"
    db_2.vm.hostname = "db-2-srv"
    db_2.vm.network "private_network", ip: "192.168.56.12"

    db_2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "db-2-server"
    end

    db_2.vm.provision "shell", inline: <<-SHELL
      dnf update -y
    #   dnf install -y mysql-server
    #   systemctl start mysqld
    SHELL
  end
  # ===== MONITORING SERVER =====
  config.vm.define "mon" do |mon|
    mon.vm.box = "generic/rocky9"
    mon.vm.hostname = "mon-srv"
    mon.vm.network "private_network", ip: "192.168.56.13"

    mon.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "monitoring-server"
    end

    mon.vm.provision "shell", inline: <<-SHELL
    #   dnf update -y
    #   dnf install -y mysql-server
    #   systemctl start mysqld
    SHELL
  end

  # ===== ANSIBLE/BACKUP SERVER =====
  config.vm.define "confm" do |confm|
    confm.vm.box = "generic/rocky9"
    confm.vm.hostname = "master-srv"
    confm.vm.network "private_network", ip: "192.168.56.14"
    confm.vm.synced_folder ".", "/vagrant", disabled: true

    confm.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ansible-server"
      guest_additions_iso = "/home/dm.ignatenko@vrgaz.ru/.config/VirtualBox/VBoxGuestAdditions_7.1.12.iso"
      if File.exist?(guest_additions_iso)
        vb.customize ["storageattach", :id,
          "--storagectl", "IDE Controller", 
          "--port", 1,
          "--device", 0,
          "--type", "dvddrive", 
          "--medium", guest_additions_iso]
      end
    end

    confm.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install epel-release -y
      dnf install kernel-devel kernel-headers gcc make perl -y 
      dnf install ansible git vim python3 python3-pip -y
      mkdir -p /mnt/cdrom
      mount /dev/cdrom /mnt/cdrom 2>/dev/null || true
      if [ -f /mnt/cdrom/VBoxLinuxAdditions.run ]; then
        echo "Устанавливаем Guest Additions..."
        sh /mnt/cdrom/VBoxLinuxAdditions.run
      else
        echo "Guest Additions ISO не найден!"
      fi
      shutdown -r now

    SHELL

  #   config.vm.provision "shell", run: "always", inline: <<-SHELL
  #     echo "Проверяем Guest Additions после перезагрузки..."
  #     # Ждем завершения загрузки
  #     sleep 10
  #     # Проверяем что Guest Additions работают
  #     if lsmod | grep -q vboxguest; then
  #     echo "Guest Additions успешно установлены!"
  #     echo "Можно монтировать shared folders"
  #     else
  #       echo "Ошибка: Guest Additions не работают!"
  #       exit 1
  #     fi
  #  SHELL

   config.vm.synced_folder "./", "/home/vagrant/project", 
    disabled: false,  # ВКЛЮЧАЕМ синхронизацию
    create: true,
    owner: "vagrant",
    group: "vagrant"
  end
end